// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// edit_search
void edit_search(std::string file, char strand, CharacterVector names, long qual, bool ex_indel, int geno_dp, int geno_hom, int edit_dp);
RcppExport SEXP editTools_edit_search(SEXP fileSEXP, SEXP strandSEXP, SEXP namesSEXP, SEXP qualSEXP, SEXP ex_indelSEXP, SEXP geno_dpSEXP, SEXP geno_homSEXP, SEXP edit_dpSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< char >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< long >::type qual(qualSEXP);
    Rcpp::traits::input_parameter< bool >::type ex_indel(ex_indelSEXP);
    Rcpp::traits::input_parameter< int >::type geno_dp(geno_dpSEXP);
    Rcpp::traits::input_parameter< int >::type geno_hom(geno_homSEXP);
    Rcpp::traits::input_parameter< int >::type edit_dp(edit_dpSEXP);
    edit_search(file, strand, names, qual, ex_indel, geno_dp, geno_hom, edit_dp);
    return R_NilValue;
END_RCPP
}
