// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// edit_search
void edit_search(std::string file, char strand, CharacterVector names, bool ex_indel, int geno_dp, int geno_hom, int edit_dp, int lh);
RcppExport SEXP editTools_edit_search(SEXP fileSEXP, SEXP strandSEXP, SEXP namesSEXP, SEXP ex_indelSEXP, SEXP geno_dpSEXP, SEXP geno_homSEXP, SEXP edit_dpSEXP, SEXP lhSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    Rcpp::traits::input_parameter< char >::type strand(strandSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< bool >::type ex_indel(ex_indelSEXP);
    Rcpp::traits::input_parameter< int >::type geno_dp(geno_dpSEXP);
    Rcpp::traits::input_parameter< int >::type geno_hom(geno_homSEXP);
    Rcpp::traits::input_parameter< int >::type edit_dp(edit_dpSEXP);
    Rcpp::traits::input_parameter< int >::type lh(lhSEXP);
    edit_search(file, strand, names, ex_indel, geno_dp, geno_hom, edit_dp, lh);
    return R_NilValue;
END_RCPP
}
// rm_search
void rm_search(CharacterMatrix x, std::string rm_file);
RcppExport SEXP editTools_rm_search(SEXP xSEXP, SEXP rm_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type rm_file(rm_fileSEXP);
    rm_search(x, rm_file);
    return R_NilValue;
END_RCPP
}
