#' ErnstEditTools: Detect and analyze RNA editing data from vcf input
#' 
#' Example data was generated by grabbing the first 5000 lines of each
#' raw .vcf file (after the header)
#'
#' Note that this package is still in development. Compiled code is
#' intended to be incorporated to dramatically improve performance.
#'
#' @docType package
#' @name editTools
NULL
