# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib editTools
#' @importFrom Rcpp sourceCpp
edit_search <- function(file, strand, names, ex_indel, geno_dp, geno_hom, edit_dp, lh) {
    invisible(.Call('editTools_edit_search', PACKAGE = 'editTools', file, strand, names, ex_indel, geno_dp, geno_hom, edit_dp, lh))
}

rm_search <- function(x, rm_file) {
    invisible(.Call('editTools_rm_search', PACKAGE = 'editTools', x, rm_file))
}

