# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib editTools
#' @importFrom Rcpp sourceCpp
edit_search <- function(file, minus, qual, ex_indel, geno_dp, geno_hom, edit_dp) {
    invisible(.Call('editTools_edit_search', PACKAGE = 'editTools', file, minus, qual, ex_indel, geno_dp, geno_hom, edit_dp))
}

